// prettier-ignore
const translation = {
  "Global": {
    "Enter": "입력",
    "Submit": "제출",
    "NoneYet!": "None yet!",
    "Cancel": "취소",
    "Confirm": "확인",
    "Accept": "수락",
    "Reject": "거부",
    "NotNow": "Not now",
    "Share": "공유",
    "Decline": "거절",
    "Back": "뒤로",
    "Next": "다음",
    "Continue": "계속",
    "Info": "정보",
    "ThisDecisionCannotBeChanged.": "이 결정은 변경할 수 없습니다.",
    "Failure": "실패",
    "Success": "성공",
    "SomethingWentWrong": "문제가 발생했습니다",
    "Done": "완료",
    "Skip": "건너뛰기",
    "View": "보기",
    "Home": "홈",
    "ErrorCode": "오류 코드",
    "Okay": "확인",
    "GoBack": "뒤로 가기",
    "GetStarted": "시작하기",
    "Dismiss": "닫기",
    "ShowDetails": "세부 정보 표시",
    "TryAgain": "다시 시도",
    "Biometrics": "생체 인식",
    "On": "켜기",
    "Off": "끄기",
    "Close": "닫기",
    "Remove": "제거"
  },
  "Date": {
    "ShortFormat": "yyyy-MM-dd",
    "LongFormat": "yyyy-MM-dd, HH:mm:ss",
    "MonthLong": {
      "January": "January",
      "February": "February",
      "March": "March",
      "April": "April",
      "May": "May",
      "June": "June",
      "July": "July",
      "August": "August",
      "September": "September",
      "October": "October",
      "November": "November",
      "December": "December",
    },
    "MonthShort": {
      "January": "Jan",
      "February": "Feb",
      "March": "Mar",
      "April": "Apr",
      "May": "May",
      "June": "Jun",
      "July": "Jul",
      "August": "Aug",
      "September": "Sep",
      "October": "Oct",
      "November": "Nov",
      "December": "Dec",
    },
    "MinuteAgo": "분 전",
    "MinutesAgo": "분 전",
    "JustNow": "방금",
  },
  "Language": {
    "English": "영어",
    "French": "불어",
    "Korean": "한국어",
    "Portuguese": "포르투갈어",
  },
  "Error": {
    "Unknown": "Unknown Error",
    "Problem": "A problem has occurred",
    "ErrorCode": "Error code",
    "Title1024": "Unable to accept credential offer.",
    "Message1024": "There was a problem while accepting the credential offer.",
    "Title1025": "Unable to reject credential offer",
    "Message1025": "There was a problem while rejecting the credential offer",
    "Title1026": "Unable to update retrieved credentials.",
    "Message1026": "There was a problem while updating retrieved credentials.",
    "Title1027": "Unable to accept proof request.",
    "Message1027": "There was a problem while accepting the proof request.",
    "Title1028": "Unable to reject proof request",
    "Message1028": "There was a problem while rejecting the proof request",
    "Title1029": "Details	Unable to update retrieved credentials.",
    "Message1029": "There was a problem while updating retrieved credentials.",
    "Title1030": "Unable to accept connection.",
    "Message1030": "There was a problem while accepting the connection redirection.",
    "Title1031": "Unable to accept connection.",
    "Message1031": "There was a problem while accepting the connection.",
    "Title1032": "Unable to remove credential.",
    "Message1032": "There was a problem while removing the credential.",
    "Title1033": "Unable to fetch credential.",
    "Message1033": "Credential could not be found.",
    "Title1034": "Unable to fetch proof request.",
    "Message1034": "Proof request could not be found.",
    "Title1035": "Unable to fetch credential offer.",
    "Message1035": "Credential offer could not be found.",
    "Title1036": "Unable to fetch wallet credentials",
    "Message1036": "Wallet credentials could not be found",
    "Title1037": "Unable to remove Contact.",
    "Message1037": "There was a problem while removing the Contact.",
    "Title1038": "Unable to generate a proof request.",
    "Message1038": "There was a problem while generating a proof request.",
  },
  "ActivityLog": {
    "Your": "Your",
    "Activity": "activity log",
    "Updated": "has been updated",
  },
  "StatusMessages": {
    "InitAgent": "Initializing agent .."
  },
  "Terms": {
    "TermsOfService": "Terms of Service",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "I Agree",
    "Attestation": "I have read, understand and accept the terms and conditions.",
  },
  "Tour": {
    "GuideTitle": "전자증명 지갑에 오신 것을 환영합니다",
    "WouldYouLike": "전자증명 지갑 사용 방법에 대해 안내를 받으시겠습니까?",
    "UseAppGuides": "앱 가이드 사용",
    "DoNotUseAppGuides": "사용 안 함",
    "AddAndShare": "전자증명서 추가 및 공유",
    "AddAndShareDescription": "전자증명서를 추가하고 사용하려면 서비스 제공자가 표시하는 QR 코드를 스캔합니다.",
    "AddCredentials": "Add credentials",
    "AddCredentialsDescription": "Add credentials by scanning a QR code displayed on the issuer service.",
    "Notifications": "알림",
    "NotificationsDescription": "QR 코드를 스캔한 후 증명 제안이나 증명 요청 등의 알림이 여기에 표시됩니다.",
    "YourCredentials": "전자지갑",
    "YourCredentialsDescription": "발급받은 전자증명서가 여기에 표시됩니다. 세부 정보를 검토하고 전자증명서를 추가하거나 삭제할 수 있습니다.",
    "CredentialOffers": "Credential offers",
    "CredentialOffersDescription": "An organization has offered you a credential. Review the credentials details and choose to accept or decline it. Accepted credentials will be added to your wallet.",
    "ProofRequests": "Proof requests",
    "ProofRequestsDescription": "An organization is asking you to prove your credentials. Review what they're asking for and choose to accept or decline it.",
    "Skip": "건너뛰기",
    "Next": "다음",
    "Back": "뒤로",
    "Done": "완료"
},
  "CameraDisclosure": {
    "AllowCameraUse": "Allow camera use",
    "CameraDisclosure": "The camera is used to scan QR codes that initiate a credential offer or credential request. No information about the images is stored, used for analytics, or shared.",
    "ToContinueUsing": "To continue using the Aries Bifold scan feature, please allow camera permissions.",
    "Allow": "Allow",
    "OpenSettings": "Open settings",
  },
  "PINCreate": {
    "Message": {
      "CrossPatternValidation": "A pattern of cross was detected in your PIN. Please try again.",
      "OddOrEvenSequenceValidation": "An odd or even sequence was detected in your PIN. Please try again.",
      "NoRepetitionOfTheSameNumbersValidation": "The PIN can't have a repetition of the same digit. Please try again.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "A repeated two-digit sequence was detected in your PIN. Please try again.",
      "NoSeriesOfNumbersValidation": "A series was detected in your PIN. Please try again.",
      "PINOnlyContainDigitsValidation": "Your PIN needs to only contain digits. Please try again.",
      "PINTooShortValidation": "Your PIN is too short. Please try again.",
      "PINTooLongValidation": "Your PIN is too long. Please try again.",
      "OldPINIncorrect": "Your old pin is incorrect. Please try again."
    },
    "Helper": {
      "CrossPatternValidation": "Does not contain a pattern of cross.",
      "OddOrEvenSequenceValidation": "Does not contain an odd or even sequence.",
      "NoRepetitionOfTheSameNumbersValidation": "Does not contain the same repeating number.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Does not contain repeating two-digit sequence.",
      "NoSeriesOfNumbersValidation": "Does not contain a series of numbers (123).",
      "PINOnlyContainDigitsValidation": "Must contain only digits.",
      "PINTooShortValidation": "The PIN is long enought.",
      "PINTooLongValidation": "The PIN is long enought.",
    },
    "UserAuthenticationPIN": "User authentication PIN",
    "PINTooShort": "PIN is too short",
    "InvalidPIN": "Invalid PIN",
    "PINsDoNotMatch": "PINs do not match",
    "PleaseUseOnlyNumbersInYourPIN": "Please use only numbers in your PIN",
    "YourPINMustBe6DigitsInLength": "Your PIN needs to be 6 digits long.",
    "EnteredPINsDoNotMatch": "The entered PINs do not match. Please try again.",
    "YouNeedToCreateA6DigitPIN": "You need to create a 6 digit PIN",
    "PleaseReenterYourPIN": "Please re-enter your PIN",
    "PinChangeSuccessTitle": "Successfully changed your PIN",
    "PinChangeSuccessMessage": "Your PIN was successsfully changed. You can now log in with your new PIN.",
    "EnterOldPINTitle": "Enter your old PIN",
    "NewPIN":"new",
    "EnterPINTitle": "Enter a 6 digit PIN",
    "EnterPIN": "등록할 PIN 번호를 입력하세요",
    "ReenterPIN": "Re-enter PIN",
    "ReenterPINTitle": "Re-Enter PIN",
    "CreatePIN": "Create PIN",
    "RememberPIN": "Create a PIN to secure your wallet.",
    "RememberChangePIN": "Change your PIN to secure your wallet.",
    "PINDisclaimer": "If you forget it, you may need to set up your wallet again and re-add your cards.",
    "Show": "Show PIN",
    "Hide": "Hide PIN",
    "ChangePIN": "Change PIN",
    "Continue": "Continue",
    "EnterYourCurrentPIN": "Enter your current PIN"
  },
  "PINEnter": {
    "EnterPIN": "PIN 번호를 입력하세요",
    "Unlock": "잠금 해제",
    "Or": "또는",
    "BiometricsUnlock": "생체 인식으로 잠금 해제",
    "IncorrectPIN": "잘못된 PIN 번호입니다.",
    "RepeatPIN": "PIN을 다시 입력해주세요.",
    "EnableBiometrics": "전자지갑을 로드하려면 생체 인식을 활성화해야 합니다.",
    "BiometricsNotProvided": "생체 인식이 제공되지 않았습니다. PIN을 사용하여 전자지갑을 로드할 수 있습니다.",
    "BiometricsError": "생체 인식이 실패했습니다.",
    "BiometricsErrorEnterPIN": "전자지갑 PIN을 입력해주세요.",
    "LoggedOut": "로그아웃 되었습니다",
    "LoggedOutDescription": "전자지갑을 5분 동안 사용하지 않아, 정보 보호를 위해 자동으로 로그아웃 되었습니다.",
    "BiometricsChanged": "기기의 생체 인식이 변경되어 생체 인식 잠금이 해제되었습니다.",
    "BiometricsChangedEnterPIN": "전자지갑 PIN을 입력해주세요.",
    "AttemptLockoutWarning": "참고: 보안을 위해 다시 잘못된 PIN을 입력하면 잠시동안 전자지갑이 잠길 수 있습니다."
  },
  "AttemptLockout": {
    "Title": "전자지갑이 일시적으로 잠겼습니다",
    "Description": "PIN을 너무 많이 잘못 입력하여 잠겼습니다.",
    "TryAgain": "다음 시간 후에 다시 시도할 수 있습니다:",
    "Hours": "시간",
    "Minutes": "분",
    "Seconds": "초",
  },
  "Biometry": {
    "Toggle": "Toggle Biometrics",
    "EnabledText1": "Unlock the wallet with your phone's biometrics instead of your wallet PIN.",
    "EnabledText2": "Using biometrics means that all fingerprints or face ID added on this phone will have access to your wallet.",
    "NotEnabledText1": "Biometrics is not currently setup on this device and therefore cannot be enabled.",
    "NotEnabledText2": "If you wish to enable this feature turn biometrics on in the device settings and then return to this screen.",
    "Warning": "Ensure only you have access to your wallet.",
    "UseToUnlock": "Use biometrics to unlock wallet?",
    "UnlockPromptTitle": "Wallet Unlock",
    "UnlockPromptDescription": "Use biometrics to unlock your wallet"
  },
  "Contacts": {
    "EmptyList": "Your Contacts is empty!",
    "TypeHere": "Type Message Here",
    "PeopleAndOrganizations": "People and organizations you've interacted with are listed here.",
    "WhatAreContacts": "What are Contacts?",
    "AddContact": "Add Contact",
  },
  "ContactDetails": {
    "Created": "Created",
    "ConnectionState": "Connection State",
    "AContact": "A Contact",
    "DateOfConnection": "Connected: {{ date }}",
    "RemoveTitle": "Remove this Contact",
    "RemoveCaption": "To add credentials, the issuing organization needs to be a Contact.",
    "UnableToRemoveTitle": "Unable to remove Contact",
    "UnableToRemoveCaption": "Unable to remove because there are credentials issued by this Contact in your wallet. Remove the credentials first then remove this Contact.",
    "GoToCredentials": "Go to Credentials",
    "RemoveContact": "Remove Contact",
    "ContactRemoved": "Contact removed",
    "RemoveContactMessageTop": "By removing this Contact you'll no longer be able to:",
    "RemoveContactMessageBottom": "This Contact will not be notified that you removed them from your Contacts",
    "RemoveContactsBulletPoint1": "Direct message this Contact",
    "RemoveContactsBulletPoint2": "Get offered new credentials from this Contact",
    "RemoveContactsBulletPoint3": "Get notified of updates to your credentials issued by this Contact",
    "RemoveContactsBulletPoint4": "Request for information from this Contact or they request information from you",
  },
  "WhatAreContacts": {
    "Title": "What are Contacts?",
    "Preamble": "Contacts are people or organizations you've interacted with.\n\nYou're connected over a secure and private line that no one but you or them can see. Nothing is shared without your permission.\n\nYou can:",
    "ListItemDirectMessage": "Direct message your Contacts",
    "ListItemNewCredentials": "Get offered new credentials",
    "ListItemNotifiedOfUpdates": "Get notified of updates to your credentials issued by them",
    "ListItemRequest": "Request for information from your Contact or they request information from you",
    "RemoveContacts": "You can always remove Contacts at any time from your",
    "ContactsLink": "Contacts list",
  },
  "Credentials": {
    "CredentialsNotFound": "Credentials not found",
    "CredentialDetails": "Credential Details",
    "EmptyList": "Your wallet is empty. Your accepted credentials will be added here.",
    "IssuedBy": "Issued by",
    "Credential": "credential"
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Created At:",
    "Version": "Version",
    "Issued": "Issued",
    "PrivacyPolicy": "Privacy policy",
    "TermsAndConditions": "Terms and conditions",
    "RemoveFromWallet": "Remove from wallet",
    "Revoked": "Revoked",
    "CredentialRevokedMessageTitle": "This credential is revoked",
    "CredentialRevokedMessageBody": "This credential may no longer work for some proof requests. You will need to update the credential with the issuer.",
    "NewRevoked": "Credential revoked",
    "RemoveTitle": "Remove credential from your wallet",
    "RemoveCaption": "You will lose your ability to prove the information on this credential with this Wallet.",
    "CredentialNotFound": "Credential not found",
    "YouWillNotLose": "You will NOT lose",
    "YouWillNotLoseListItem1": "Your credential within the system that issued you your credential.",
    "YouWillNotLoseListItem2": "The issuing organization as a Contact.",
    "HowToGetThisCredentialBack": "How to get this credential back",
    "HowToGetThisCredentialBackListItem1": "You will have to go to the organization that issued you this credential and request it again.",
    "CredentialRemoved": "Credential removed",
    "IssuedBy": "Issued by:",
    "RemoveCredential": "Remove Credential",
  },
  "Home": {
    "Welcome": "환영합니다",
    "Notification": "알림",
    "Notifications": "알림",
    "OneNotification": "1개의 알림",
    "CountNotifications": "{{ count }}개의 알림",
    "NoNewUpdates": "새로운 알림이 없습니다.",
    "NoCredentials": "전자지갑에 발급받은 전자증명서가 없습니다.",
    "SeeAll": "모두 보기",
    "YouHave": "귀하의",
    "Credential": "전자증명서가",
    "Credentials": "전자증명서가",
    "InYourWallet": "전자지갑에 있습니다",
    "NewMessage": "새 메시지",
    "SentMessage": "메시지를 보냈습니다",
    "ReceivedMessage": "새 메시지를 받았습니다",
    "ViewMessage": "메시지 보기",
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Successfully Accepted Connection",
    "AcceptingConnection": "Accepting Connection",
    "ConnectionRecordIdNotFound": "Connection record ID not found",
    "ConnectionAccepted": "Connection Accepted",
    "ConnectionNotFound": "Connection not found",
    "InvalidQrCode": "Invalid QR code. Please try again.",
    "WillScanAutomatically": "A valid QR code will scan automatically.",
    "ScanQRCode": "Scan QR code",
    "MyQRCode": "My QR code",
    "UnableToHandleRedirection": "Unable to handle redirection",
    "Close": "Close",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Just a moment while we make a secure connection...",
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
    "ConnectionInvitation": "Connection Invitation",
    "ScanQR": "Show this QR code to the other person",
    "ScanQRComment": "After the QR code is scanned, a connection will be created.",
    "ShareQR": "Sharing this QR code with someone will add them as a Contact.",
    "MakingConnection": "Making connection...",
    "ConnectionCompleted": "Connection completed!",
    "Toggle": "Toggle Connection Inviter Capability",
    "UseConnectionInviterCapability": "Use connection inviter capability?",
    "OpenContact": "Open Contact",
  },
  "ConnectionAlert": {
    "AddedContacts": "Added to Contacts",
    "WhatAreContacts": "What are Contacts?",
    "NotificationBodyUpper": "You can find ",
    "NotificationBodyLower": " in your Contacts. Manage your Contacts in Settings",
    "PopupIntro": "Adding organizations as a Contact will allow you to:",
    "PopupPoint1": "Get updates to credentials issued by this organization",
    "PopupPoint2": "Get offered new credentials",
    "PopupPoint3": "Fast-track proof requests",
    "SettingsLink": "Settings",
    "SettingsInstruction": "You can always remove Contacts at anytime in ",
    "PrivacyMessage": "Use of your credentials is never shared with your Contacts.",
    "PopupExit": "Got it"
  },
  "CredentialOffer": {
    "CredentialOffer": "Credential Offer",
    "ThisIsTakingLongerThanExpected": "This is taking Longer than expected. Check back later for your new credential.",
    "RejectThisCredential?": "Reject this Credential?",
    "AcceptingCredential": "Accepting Credential",
    "SuccessfullyAcceptedCredential": "Successfully Accepted Credential",
    "RejectingCredential": "Rejecting Credential",
    "SuccessfullyRejectedCredential": "Successfully Rejected Credential",
    "CredentialNotFound": "Credential not found",
    "CredentialAccepted": "Credential Accepted",
    "CredentialRejected": "Credential Rejected",
    "CredentialAddedToYourWallet": "Credential added to your wallet",
    "CredentialDeclined": "Credential declined",
    "CredentialOnTheWay": "Your credential is on the way",
    "NewCredentialOffer": "New Credential Offer",
    "IsOfferingYouACredential": "is offering you a credential",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this credential?",
    "ConfirmDeclinedMessage": "In order to receive the credential offer again, you will need to reapply with the issuer.",
    "ConfirmDecline": "Yes, decline this credential",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline credential offer?",
    "Declined": "Declined",
    "DeclineParagraph1": "In order to receive the credential offer again, you will need to restart the issuing process again with the issuing service.",
    "DeclineParagraph2": "Are you sure you want to decline this credential offer?",
    "CustomOfferTitle": "Delete this offer?",
    "CustomOfferParagraph1": "Deleting this offer will remove the notification from your list.",
    "CustomOfferParagraph2": "Don't recongize the organization? Check your Contact list. you only recieve notifications from Contacts you've initiated.",
    "DeleteOfferTitle": "Delete this offer?",
    "DeleteOfferMessage": "Deleting this offer will remove the notification from your list.",
    "DeleteOfferDescription": "Don't recognize the organization? Check your Contacts list. You only receive notifications from Contacts you've initiated",
  },
  "ProofRequest": {
    "ProofRequest": "Proof Request",
    "RequestProcessing": "Just a moment...",
    "OfferDelay": "Offer delay",
    "RejectThisProof?": "Reject this Proof Request?",
    "DeclineThisProof?": "Decline this Proof Request?",
    "AcceptingProof": "Accepting Proof",
    "SuccessfullyAcceptedProof": "Successfully Accepted Proof",
    "ProofRequestNotFound": "Proof request not Found",
    "RejectingProof": "Rejecting Proof",
    "ProofAccepted": "Proof Accepted",
    "ProofRejected": "Proof Rejected",
    "RequestedCredentialsCouldNotBeFound": "Requested credentials could not be found",
    "NewProofRequest": "New Proof Request",
    "NotAvailableInYourWallet": "Not available",
    "PredicateNotSatisfied": "Requirement not met",
    "IsRequesting": "is requesting",
    "IsRequestingSomethingYouDontHaveAvailable": "is requesting something you don't have available",
    "YouDoNotHaveDataPredicate": "You do not meet the requirements of this proof request from",
    "IsRequestingYouToShare": "is requesting the following information from",
    "Credential": "credential.",
    "Credentials": "credentials.",
    "WhichYouCanProvideFrom": "which you can provide from",
    "Details": "Details",
    "SendingTheInformationSecurely": "Sending the information securely",
    "InformationSentSuccessfully": "Information sent successfully",
    "NewProof": "New Proof",
    "ProofRequestDeclined": "Proof request declined",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this proof request?",
    "ConfirmDeclinedMessage": "In order to receive the proof request again, the requestor will need to resend it.",
    "ConfirmDecline": "Yes, decline this proof request",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline proof request?",
    "Declined": "Declined",
    "ReviewSentInformation_one": "You shared the following information from {{count}} credential with",
    "ReviewSentInformation_other": "You shared the following information from {{count}} credentials with",
    "ShareFollowingInformation_one": "is sharing the following information from {{count}} credential.",
    "ShareFollowingInformation_other": "is sharing the following information from {{count}} credentials.",
    "DeclineBulletPoint1": "Organizations and services require that you prove you're eligible to continue with their service or access.",
    "DeclineBulletPoint2": "In order to receive the proof request again, you will need to restart the process with the service.",
    "DeclineBulletPoint3": "Are you sure you want to decline this proof request?",
  },
  "Settings": {
    "Version": "Version",
    "VersionString": "0.0.0-0",
    "AppSettings": "앱 설정",
    "AboutApp": "About App",
    "ChangePin": "Change PIN",
    "Language": "언어",
    "DataRetention": "Data retention",
    "PreventAutoLock": "Prevent auto-lock",
    "TogglePreventAutoLock": "Toggle prevent auto-lock",
    "AppGuides": "App guides",
    "Build": "Build",
    "WhatAreContacts": "What are Contacts?",
    "ScanMyQR": "Scan my QR code",
    "Help": "Help",
    "MoreInformation": "More information",
    "Developer": "Developer options"
  },
  "TabStack": {
    "Home": "홈",
    "Scan": "Scan",
    "Credentials": "전자지갑",
  },
  "RootStack": {
    "Contacts": "Contacts",
    "Settings": "Settings"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permission to use camera",
    "WeNeedYourPermissionToUseYourCamera": "We need your permission to use your camera",
    "Ok": "Ok",
  },
  "QRRender": {
    "GenerationError": "Unable to generate QR code",
  },
  "Record": {
    "Hide": "Hide",
    "Show": "Show",
    "HideAll": "Hide all",
    "ShowAll": "Show all",
    "Hidden": "Hidden",
    "InvalidDate": "Invalid Date: ",
    "Zoom": "Zoom",
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Onboarding",
    "Terms": "Terms & Conditions",
    "CreatePIN": "PIN 등록",
    "EnterPIN": "PIN 입력",
    "Home": "Home",
    "Scan": "Scan",
    "Credentials": "전자지갑",
    "CredentialDetails": "전자인증서",
    "Notifications": "알림",
    "CredentialOffer": "전자인증서 발급",
    "ProofRequest": "증명 요청",
    "ProofRequestDetails": "Proof Request Details",
    "ProofRequestAttributeDetails": "Proof Request Attribute Details",
    "ProofDetails": "Proof Details",
    "Settings": "Settings",
    "Tours": "App guides",
    "Language": "Language",
    "DataRetention": "Data retention",
    "Contacts": "Contacts",
    "Decline": "Decline",
    "ContactDetails": "Contact Details",
    "Biometry": "Biometrics",
    "Developer": "Developer options",
    "ChangePIN": "Change PIN",
    "CommonDecline": "Decline",
    "ProofRequests": "Proof requests",
    "SendProofRequest": "Send a proof request",
    "ChooseProofRequest": "Choose a proof request",
    "ProofRequestUsageHistory": "Usage History",
    "CreateConnectionInvitation": "Create a connection invitation",
    "AttemptLockout": "Temporarily Locked",
    "OnTheWay": 'On The Way',
    "Declined": 'Declined',
    "UseBiometry": 'Use Biometry',
    "CustomNotification": 'Custom Notification',
    "ProofRequesting": 'Proof Requesting',
    "NameWallet": "Name your wallet",
  },
  "Loading": {
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
    "BackToHome": "Go back to home"
  },
  "NameWallet": {
    "EnableWalletNaming": "Enable wallet naming?",
    "ToggleWalletNaming": "Toggle wallet naming",
    "NameYourWallet": "Name your wallet",
    "ThisIsTheName": "This is the name people see when connecting with you.",
    "CharCountTitle": "Character count exceeded",
    "CharCountDescription": "You've exceeded the maximum character count of 50 characters. Please reduce your character count.",
    "EmptyNameTitle": "Wallet name can't be empty",
    "EmptyNameDescription": "This is the name people see when connecting with you.\n\nPlease enter a wallet name.",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "No internet connection",
    "NoInternetConnectionMessage": "You're unable to access services using Bifold or receive credentials until you're back online.\n\nPlease check your internet connection.",
    "LedgerConnectivityIssueTitle": "Wallet Services",
    "LedgerConnectivityIssueMessage": "A firewall may be preventing you from connecting to wallet related services.",
  },
  "Onboarding": {
    "SkipA11y": "Skip introduction to Aries Bifold",
  },
  "Chat": {
    "OpenPresentation": "Open presentation",
    "ViewRequest": "View request",
    "ViewOffer": "View offer",
    "OpenItem": "열기",
    "UserYou": "당신은",
    "YouConnected": "You connected with",
    "CredentialProposalSent": "전자증명 제안을 보냈습니다",
    "CredentialOfferReceived": "전자증명 제안을 받았습니다",
    "CredentialRequestSent": "전자증명 요청을 보냈습니다",
    "CredentialDeclined": "전자증명 제안을 거절했습니다",
    "CredentialReceived": "전자증명서를 받았습니다",
    "ProofRequestSent": "증명 요청을 보냈습니다",
    "ProofPresentationReceived": "정보를 보냈습니다",
    "ProofRequestReceived": "증명 요청을 받았습니다",
    "ProofRequestRejected": "증명 요청을 거절했습니다",
    "ProofRequestRejectReceived": "증명 요청을 거절했습니다",
    "ProofRequestSatisfied": "정보를 공유했습니다"
  },
  "Verifier": {
    "UseVerifierCapability": "Use Verifier capability?",
    "AcceptDevCredentials": "Accept non-production credentials?",
    "UseDevVerifierTemplates": "Use development verifier templates?",
    "Toggle": "Toggle Verifier Capability",
    "ToggleDevTemplates": "Toggle Verifier Development Templates",
    "ProcessingProof": "Just a moment...",
    "ZeroKnowledgeProof": "Zero-knowledge proof",
    "Parameterizable": "Parameterizable",
    "RefreshQR": "Refresh QR Code",
    "GenerateNewQR": "Request another proof",
    "ShareLink": "Share link",
    "ScanQR": "Show this QR code to the other person",
    "ScanQRComment": "After the QR code is scanned, a proof request will be sent.",
    "InformationReceived": "Information received.",
    "InformationReceivedDetails": "Review the information below.",
    "ProofVerificationFailed": "Proof verification failed",
    "ViewDetails": "View details",
    "HideDetails": "Hide details",
    "UseProofRequest": "Use this proof request",
    "SendThisProofRequest": "Send this proof request",
    "SendProofRequest": "Send a Proof Request",
    "EmptyList": "Your wallet is empty. Your proof request templates will be added here.",
    "ShowTemplateUsageHistory": "Show usage history",
    "RequestSent": "Presentation request sent",
    "PresentationDeclined": "Presentation request declined",
    "PresentationReceived": "Presentation received",
    "PresentationFailed": "Presentation failed",
    "ProofRequestRejected": "Presentation request rejected",
    "PresentationFrom": "From",
    "PresentationState": "State",
    "ConnectionlessPresentation": "Connectionless",
    'TutorialStep1Title': 'Show this QR code to the other person',
    'TutorialStep1Description': 'You will connect with the other person. They will receive a proof request.',
    "InvalidPredicateValueTitle": "Invalid value for {{ predicate }}",
    "InvalidPredicateValueDetails": "Must be a number",
    "ConnectionLessLabel": "Anonymous",
  }
}

export default translation
